POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Goku",
  "email": "goku@mail.com"
}

###

GET http://localhost:3333/invites/naruto123

###

GET http://localhost:3333/subscribers/naruto123/ranking/clicks