@baseUrl = http://localhost:3333
@firstUserId = 

POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Primeiro usuário",
  "email": "first@mail.com",
}

###

POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
  "name": "Segundo usuário",
  "email": "second@mail.com",
  "referrer": {{firstUserId}}
}

###

GET {{baseUrl}}/invites/{{firstUserId}}

###

GET {{baseUrl}}/subscribers/{{firstUserId}}/ranking/clicks

###

GET {{baseUrl}}/subscribers/{{firstUserId}}/ranking/count

###

GET {{baseUrl}}/subscribers/{{firstUserId}}/ranking/position

###

GET {{baseUrl}}/ranking